-- Move the "prune on the first absence" arming from the item rows to the query row.
--
-- Editing a query's search string means the next full walk is authoritative for a
-- definition the cache has never seen: whatever it doesn't return is stale by
-- construction, not a paging race, so it should go without waiting for a second
-- strike. `db::update_query` expressed that by pre-loading every cached row's
-- `missing_count` to `PRUNE_STRIKES - 1`. Two problems with that:
--
--   * It rewrites up to `max_items_per_query` rows to change one integer. The rows
--     carry `body`, so a 1000-item query wrote several MB of pages while holding the
--     write lock, in the middle of an interactive edit.
--   * `missing_count = 1` then meant two different things — "armed by an edit" and
--     "observed absent once" — with no way to tell them apart and so no way to expire
--     the first. An incremental sync in between disarmed only the rows it returned
--     (`upsert_items` zeroes the counter), leaving every un-updated row armed
--     indefinitely. A full walk arriving much later — possibly racing an update —
--     would delete those on their first absence, which is exactly what corroboration
--     exists to prevent.
--
-- The flag is set by `update_query` on a changed search string, and read, applied and
-- cleared inside `db::prune_missing_items`' transaction, so it covers exactly one walk:
-- the first whose pages came from the new definition. That is the expiry the row-state
-- version could not have. It lives in that transaction because a clear that could fail
-- after the delete committed would leave an arm alive past the walk it was set for --
-- the same failure in miniature.
--
-- The read matches on `queries.query`, not just the id, against the string the walk is
-- actually paging. A walk can be on a stale definition for two reasons -- a second
-- front-end never hears about the edit (`QueryUpdated` reaches the editing process only,
-- and the cache is shared), and a queued `SyncJob` carries the string snapshotted when it
-- was enqueued -- and such a walk must neither take the arm nor spend it. Timing alone
-- does not separate those cases, which is why the definition is the key rather than the
-- moment of the read.
--
-- A query whose result set stays truncated never prunes and so never spends its arm. That
-- is inert while it lasts, since only a prune reads the flag; if the result set later
-- drops below the cap, the first walk that can prune is also the first to have validated
-- the cache against the new definition, so it is the walk the arm was for.
--
-- `missing_count` is left alone. Rows still sitting at 1 from an edit before this
-- migration are indistinguishable from rows genuinely absent once, and the harmless
-- reading is the conservative one — they need a second absence, and any search that
-- returns them resets the counter to 0.
ALTER TABLE queries ADD COLUMN prune_armed INTEGER NOT NULL DEFAULT 0;
